# Generated by Django 4.2 on 2025-09-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_created_at_alter_user_password_alter_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="icon",
            field=models.CharField(
                default="https://cdn2.iconfinder.com/data/icons/christmas-holiday-10/256/reindeer_avatar.png",
                max_length=500,
            ),
        ),
    ]
