# Generated by Django 4.2 on 2025-09-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="icon",
            field=models.TextField(
                default="https://cdn2.iconfinder.com/data/icons/christmas-holiday-10/256/reindeer_avatar.png"
            ),
        ),
    ]
