# Generated by Django 4.2 on 2025-09-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(blank=True, to="users.user"),
        ),
        migrations.DeleteModel(
            name="Friends",
        ),
    ]
